### ISSUE TITLE
Search on the site

### ISSUE THREAD

**Issue by deyw-bit** [jlopp/lopp.net#636] opened 2021-01-25 10:29 UTC
I'm missing a search functionality on the lopp.net site. Search would be quite useful for the bitcoin resources area at least.

**Comment by jlopp** [comment] 2021-01-25 12:21
Dupe of #557 - I'm all ears for any simple search functionality that doesn't require a custom back end. I'm not sure if there's an option that's better than just using google's site-specific search.

**Closed by jlopp** 2021-01-25 12:21 UTC
